services:
  mongo: 
    container_name: ${MONGO_DB_NAME}
    image: mongo:8.0
    volumes:
      - ./db:/data/db
    ports:
      - ${MONGO_PORT}:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    command: ["--auth"]
  
